apiVersion: v1
kind: Template
labels:
  app: dummy-service
  template: dummy-service-bluegreen
metadata:
  annotations:
    iconClass: icon-java
    tags: microservice,jboss,spring
  name: dummy-service-bluegreen
objects:
# Dummy Service Service - Blue
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: dummy-service-blue
    labels:
      app: dummy-service
      variant: blue
  spec:
    replicas: 1
    selector:
      deploymentconfig: dummy-service-blue
    strategy:
      resources: {}
      type: Recreate
    template:
      metadata:
        labels:
          app: dummy-service
          variant: blue
          deploymentconfig: dummy-service-blue
        name: dummy-service-blue
      spec:
        containers:
        - env:
          - name: OPENSHIFT_KUBE_PING_LABELS
            value: application=dummy-service-blue
          - name: OPENSHIFT_KUBE_PING_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: dummy-service:prod-blue
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /status
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5
            periodSeconds: 10
          name: dummy-service
          ports:
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 8888
            name: ping
            protocol: TCP
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /status
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            successThreshold: 1
            timeoutSeconds: 1
            periodSeconds: 10
          resources:
            limits:
              cpu: 2
              memory: 2Gi
            requests:
              cpu: 200m
              memory: 1Gi
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 20
    triggers:
    - imageChangeParams:
        automatic: false
        containerNames:
        - dummy-service
        from:
          kind: ImageStreamTag
          name: dummy-service:${APP_VERSION_BLUE}
          namespace: ${NAMESPACE}
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
    labels:
      app: dummy-service-live
      variant: blue
    name: dummy-service-blue
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: dummy-service-blue
# Dummy Service - Green
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: dummy-service-green
    labels:
      app: dummy-service
      variant: green
  spec:
    replicas: 1
    selector:
      deploymentconfig: dummy-service-green
    strategy:
      resources: {}
      type: Recreate
    template:
      metadata:
        labels:
          app: dummy-service
          variant: green
          deploymentconfig: dummy-service-green
        name: dummy-service-green
      spec:
        containers:
        - env:
          - name: OPENSHIFT_KUBE_PING_LABELS
            value: application=dummy-service-green
          - name: OPENSHIFT_KUBE_PING_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: dummy-service:prod-green
          imagePullPolicy: Always
          lifecycle:
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /status
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          name: dummy-service
          ports:
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 8888
            name: ping
            protocol: TCP
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /status
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 2
              memory: 2Gi
            requests:
              cpu: 200m
              memory: 1Gi
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 20
    triggers:
    - imageChangeParams:
        automatic: false
        containerNames:
        - dummy-service
        from:
          kind: ImageStreamTag
          name: dummy-service:${APP_VERSION_GREEN}
          namespace: ${NAMESPACE}
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
    labels:
      app: dummy-service-idle
      variant: green
    name: dummy-service-green
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: dummy-service-green
#Routes
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: dummy-service
      variant: green
    name: dummy-service
  spec:
    host: dummy-service-${NAMESPACE}.${HOSTNAME_SUFFIX}
    port:
      targetPort: 8080
    alternateBackends:
    - name: dummy-service-green
      weight: "0"
    to:
      kind: Service
      name: dummy-service-blue
      weight: "100"
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: dummy-service
      variant: blue
    name: dummy-service-notlive
  spec:
    host: dummy-service-notlive-${NAMESPACE}.${HOSTNAME_SUFFIX}
    port:
      targetPort: 8080
    alternateBackends:
    - name: dummy-service-blue
      weight: "0"
    to:
      kind: Service
      name: dummy-service-green
      weight: "100"


parameters:
- description: Namespace
  displayName: Namespace (development, test, prod)
  name: NAMESPACE
  required: true
- description: Hostname suffix used for routes e.g. dummy-service-<HOSTNAME_SUFFIX>
  displayName: Hostname suffix used for routes
  name: HOSTNAME_SUFFIX
  required: true
  value: apps.127.0.0.1.nip.io
- description: CoolStore application image version to be deployed (imagestreams should exist)
  displayName: CoolStore blue (existing) image version
  name: APP_VERSION_BLUE
  required: true
  value: prod-blue
- description: CoolStore application image version to be deployed (imagestreams should exist)
  displayName: CoolStore green (new) image version
  name: APP_VERSION_GREEN
  required: true
  value: prod-green
